services:
  # grafana:
  #   init: true
  #   image: grafana/grafana
  #   container_name: grafana
  #   network_mode: host
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /mnt/data/grafana:/var/lib/grafana
  #     - /etc/grafana/provisioning:/etc/grafana/provisioning
  #   restart: always
