services:
  # openai:
  #   init: true
  #   image: openai/openai
  #   container_name: openai
  #   network_mode: host
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /mnt/data/openai:/var/lib/openai
  #     - /etc/openai/provisioning:/etc/openai/provisioning
  #   restart: always
